name: Command Output
description: Run a command and store its output
inputs:
  run:
    description: Command to run
    required: true
  shell:
    description: Shell used to run command
    required: false
    default: bash
outputs:
  stdout:
    description: Output of the command
  stderr:
    description: Error of the command
branding:
  icon: terminal
  color: gray-dark

runs:
  using: "composite"
  steps:
    uses: docker://public.ecr.aws/unocha/unified-builder:8.0-stable
    with:
      run: nodejs dist/main.js
