name: "Drupal Updates Workflow"
description: "Does aall the magic."

inputs:
    flowdock_token:
    description: "The flowdock token"
    required: false
    type: string

runs:
  using: "composite"
  steps:
  - name: Composer Update
    id: update
    uses: kawax/composer-update-action@v2
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GIT_NAME: 'unocha-jenkins'
      GIT_EMAIL: 'ops+github@reliefweb.int'
      APP_SINGLE_BRANCH: 1
      APP_SINGLE_BRANCH_POSTFIX: -updated
      GIT_COMMIT_PREFIX: '[UPDATE] '
      COMPOSER_PACKAGES: 'druypal/*'

  - name: Flowdock Failure
    id: failure
    if: failure()
    uses: docker://ghcr.io/un-ocha/actions:flowdock-notify-main
    env:
      FLOWDOCK_TOKEN: ${{ inputs.flowdock_token }}
      FLOWDOCK_ICON: ${{ inputs.flowdock_icon_failure }}
      FLOWDOCK_MESSAGE: 'Failed to composer updates for ${{ github.ref }}, please go check [GitHub](https://github.com/${{ github.repository }}/actions/workflows/updates.yml).'
      FLOWDOCK_TAGS: 'update,composer,${{ github.actor }}'

  - name: Flowdock Success
    id: success
    if: success()
    uses: docker://ghcr.io/un-ocha/actions:flowdock-notify-main
    env:
      FLOWDOCK_TOKEN: ${{ inputs.flowdock_token }}
      FLOWDOCK_ICON: ${{ inputs.flowdock_icon_success }}
      FLOWDOCK_MESSAGE: 'Found composer updates for ${{ github.ref }} and made a new pull request.'
      FLOWDOCK_TAGS: 'update,composer,${{ github.actor }}'
