name: "List Drupal Issues"
description: "Updates all specified composer packages and creates a pull request with the changes."

runs:
  using: "composite"
  steps:
  - name: Drupal Issues
    id: versions
    uses: cafuego/command-output@main
    with:
      run: |
        grep -r '@see https://www.drupal.org/ ' html/modules/custom/ | awk '{ gsub("html/modules/custom//", "", $1); file=$1; gsub(":", "", file) } { printf("%-52s (%s)\n", $NF, file) }'
    continue-on-error: false
