name: 'Determine Environment Action'
description: 'Runs `determine-env`. Exports a variable for you to use in subsequent actions.'
author: 'cafuego'
branding:
  icon: 'arrow-up-right'
  color: 'orange'
inputs:
  branch_production:
    description: "The branch to consider the production branch. Defaults to 'main'."
outputs:
  branch_environment:
    description: "Either `'production'` when the current checkout is the production branch or a tag, or the branch name if not."
runs:
  uses: 'docker://unocha/actions:determine-environment-main'
'
