name: 'Extract PHP Version Action'
description: 'Runs `extract-php-version`. Exports a variable for you to use in subsequent actions.'
author: 'cafuego'
branding:
  icon: 'arrow-up-right'
  color: 'orange'
inputs:
  docker_file:
    description: "The name of the file to process for docker images."
  docker_image:
    description: "THe docker image name to check for the version."
outputs:
  php_version:
    description: "The detected PHP version in MAJOR.MINOR format."
runs:
  uses: 'docker://ghcr.io/un-ocha/actions:extract-php-version-main'
