name: "Drupal Docker Build Workflow"
description: "Does docker authentication, build, push and notification."

inputs:
  aws_role:
    description: "An AWS IAM role ARN with permission to perform ECR pull and push"
    required: true
    type: string
  aws_region:
    descripion: "An AWS region ID"
    required: false
    default: "us-east-1"
    type: string
  aws_account:
    description: "An AWS account ID that owns any (private) registries used."
    required: false
    default: '532768535361'
    type: string
  docker_registry_url:
    description: "The docker registry URL"
    required: true
    type: string
  docker_registry_path:
    description: "The docker registry path (organisation) component"
    required: false
    default: '/'
    type: string
  docker_image:
    description: "The docker image name"
    required: true
    type: string
  docker_file:
    description: "The (relative) path to the Dockerfile to use for the build"
    required: false
    default: 'docker/Dockerfile'
    type: string
  ecr_jenkins_token:
    description: "An authentication token for GitHub to access Jenkins"
    required: false
    type: string
  slack_bot_token:
    description: "The secret slack authentication token"
    require: false
    type: string
  slack_channel_name:
    description: "The slack channel to send the message to"
    require: false
    type: string

runs:
  using: "composite"
  steps:
  - name: Configure AWS Credentials
    id: credentials
    uses: aws-actions/configure-aws-credentials@v6
    with:
      role-to-assume: ${{ inputs.aws_role }}
      role-session-name: ${{ github.run_id }}
      aws-region: ${{ inputs.aws_region }}

  - name: Login to Amazon ECR
    id: login-ecr
    uses: aws-actions/amazon-ecr-login@v2
    with:
      registry-type: public

  - name: Login to Private ECR
    id: login-private
    if: endsWith(inputs.docker_registry_url, '.amazonaws.com')
    uses: aws-actions/amazon-ecr-login@v2
    with:
      registry-type: private
      registries: ${{ inputs.aws_account }}

  - name: Image Metadata
    id: meta
    run: |
      export DOCKER_TAG="${GITHUB_REF#refs/*/}"
      export DOCKER_TAG=${DOCKER_TAG//[^[:alnum:].-]/-}
      echo "DOCKER_TAG=${DOCKER_TAG}" >> $GITHUB_OUTPUT
      export VCS_REF=`git rev-parse --short HEAD`
      echo "VCS_REF=${VCS_REF}" >> $GITHUB_OUTPUT
      export VCS_URL=`git config --get remote.origin.url | sed 's#git@github.com:#https://github.com/#'`
      echo "VCS_URL=${VCS_URL}" >> $GITHUB_OUTPUT
      export BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
      echo "BUILD_DATE=${BUILD_DATE}" >> $GITHUB_OUTPUT
    shell: bash

  - name: Build docker image
    id: build
    uses: docker/build-push-action@v7
    with:
      build-args: |
        BRANCH_ENVIRONMENT=${BRANCH_ENVIRONMENT}
        VCS_REF=${{ steps.meta.outputs.VCS_REF }}
        VCS_URL=${{ steps.meta.outputs.VCS_URL }}
        BUILD_DATE=${{ steps.meta.outputs.BUILD_DATE }}
        GITHUB_ACTOR=${{ github.actor }}
        GITHUB_REPOSITORY=${{ github.repository }}
        GITHUB_SHA=${{ github.sha }}
        GITHUB_REF=${{ github.ref }}
      labels: |
        info.humanitarianresponse.build.date=${{ steps.meta.outputs.BUILD_DATE }}
        info.humanitarianresponse.build.person=${{ github.actor }}
        info.humanitarianresponse.build.vcs-url=${{ steps.meta.outputs.VCS_URL }}
        info.humanitarianresponse.build.vcs-ref=${{ steps.meta.outputs.VCS_REF }}
      file: ${{ inputs.docker_file }}
      push: true
      tags: ${{ inputs.docker_registry_url }}${{ inputs.docker_registry_path }}${{ inputs.docker_image }}:${{ steps.meta.outputs.DOCKER_TAG }}
    continue-on-error: false

  - name: Webhook
    id: webhook
    if: success() && inputs.ecr_jenkins_token
    env:
      DOCKER_IMAGE: ${{ inputs.docker_image }}
      DOCKER_TAG: ${{ steps.meta.outputs.DOCKER_TAG }}
      JENKINS_TOKEN: ${{ inputs.ecr_jenkins_token }}
    run: |
      curl -H "Token: ${JENKINS_TOKEN}" -X POST "https://jenkins.aws.ahconu.org/generic-webhook-trigger/invoke?DOCKER_IMAGE=${DOCKER_IMAGE}&DOCKER_TAG=${DOCKER_TAG}"
    shell: bash

  - name: Slack Notification
    id: slack_notification
    if: inputs.slack_bot_token && inputs.slack_channel_name
    uses: slackapi/slack-github-action@v3
    with:
      method: chat.postMessage
      token: ${{ inputs.slack_bot_token }}
      payload: |
        {
          "channel": "${{ inputs.slack_channel_name }}",
          "text": "Docker build for ${{ inputs.docker_image }}",
          "attachments": [
            {
              "color": "${{ env.SLACK_COLOR }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Docker image build ${{ job.status }} for `${{ inputs.docker_image }}:${{ steps.meta.outputs.DOCKER_TAG }}` from ${{ github.ref }} (<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Details>)"
                  }
                }
              ]
            }
          ]
        }
    env:
      SLACK_COLOR: ${{ job.status == 'success' && '#36A64F' || '#FF0000' }}
